### ISSUE TITLE
Allow using other JSON codecs

### ISSUE THREAD

**Issue by angelsl** [ex-aws/ex_aws_sts#20]
Poison is hardcoded here:

https://github.com/ex-aws/ex_aws_sts/blob/b5393dc76a9105558466a89444f4c6afe338cc79/lib/ex_aws/sts.ex#L151

**Comment by aloukissas** [comment]
Was about to file the same thing. Could generate a PR to make this configurable (e.g. use `Jason`).

**Comment by vanetix** [comment]
If either one of you have time to take a stab at this sometime this week that would be awesome, if not I'll have some time this weekend to knock this out. 

As always, thanks for the catch here!
